# Site settings
title: WHDD
email: andrey.krieger.utkin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/whdd" # the subpath of your site, e.g. /blog/
url: "http://krieger-od.github.io" # the base hostname & protocol for your site
github_username:  krieger-od

# Build settings
markdown: kramdown
